/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsOldRouteImport } from './routes/stats-old'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsOldRouteImport } from './routes/reviews-old'
import { Route as PortfolioOldRouteImport } from './routes/portfolio-old'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutOldRouteImport } from './routes/about-old'
import { Route as IndexRouteImport } from './routes/index'

const StatsOldRoute = StatsOldRouteImport.update({
  id: '/stats-old',
  path: '/stats-old',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsOldRoute = ReviewsOldRouteImport.update({
  id: '/reviews-old',
  path: '/reviews-old',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioOldRoute = PortfolioOldRouteImport.update({
  id: '/portfolio-old',
  path: '/portfolio-old',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOldRoute = AboutOldRouteImport.update({
  id: '/about-old',
  path: '/about-old',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-old': typeof AboutOldRoute
  '/contact': typeof ContactRoute
  '/portfolio-old': typeof PortfolioOldRoute
  '/reviews-old': typeof ReviewsOldRoute
  '/services': typeof ServicesRoute
  '/stats-old': typeof StatsOldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-old': typeof AboutOldRoute
  '/contact': typeof ContactRoute
  '/portfolio-old': typeof PortfolioOldRoute
  '/reviews-old': typeof ReviewsOldRoute
  '/services': typeof ServicesRoute
  '/stats-old': typeof StatsOldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-old': typeof AboutOldRoute
  '/contact': typeof ContactRoute
  '/portfolio-old': typeof PortfolioOldRoute
  '/reviews-old': typeof ReviewsOldRoute
  '/services': typeof ServicesRoute
  '/stats-old': typeof StatsOldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-old'
    | '/contact'
    | '/portfolio-old'
    | '/reviews-old'
    | '/services'
    | '/stats-old'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-old'
    | '/contact'
    | '/portfolio-old'
    | '/reviews-old'
    | '/services'
    | '/stats-old'
  id:
    | '__root__'
    | '/'
    | '/about-old'
    | '/contact'
    | '/portfolio-old'
    | '/reviews-old'
    | '/services'
    | '/stats-old'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutOldRoute: typeof AboutOldRoute
  ContactRoute: typeof ContactRoute
  PortfolioOldRoute: typeof PortfolioOldRoute
  ReviewsOldRoute: typeof ReviewsOldRoute
  ServicesRoute: typeof ServicesRoute
  StatsOldRoute: typeof StatsOldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats-old': {
      id: '/stats-old'
      path: '/stats-old'
      fullPath: '/stats-old'
      preLoaderRoute: typeof StatsOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews-old': {
      id: '/reviews-old'
      path: '/reviews-old'
      fullPath: '/reviews-old'
      preLoaderRoute: typeof ReviewsOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-old': {
      id: '/portfolio-old'
      path: '/portfolio-old'
      fullPath: '/portfolio-old'
      preLoaderRoute: typeof PortfolioOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-old': {
      id: '/about-old'
      path: '/about-old'
      fullPath: '/about-old'
      preLoaderRoute: typeof AboutOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutOldRoute: AboutOldRoute,
  ContactRoute: ContactRoute,
  PortfolioOldRoute: PortfolioOldRoute,
  ReviewsOldRoute: ReviewsOldRoute,
  ServicesRoute: ServicesRoute,
  StatsOldRoute: StatsOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
